### ISSUE TITLE
Extender schedules pods on nodes that have reached request limits

### ISSUE THREAD

**Issue by shelleybess** [libopenstorage/stork#114]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:

Extender scheduled pods to be created on a node that was at request limits resulting in failed pods with OutOfmemory error. Using default scheduler resulted in successful deployment.

**What you expected to happen**:

Pods would be scheduled on nodes with enough resources.

**How to reproduce it (as minimally and precisely as possible)**:

Start a pod that will use a volume located on a node near memory request limits. The pod will need to request more memory than the node has available. Other nodes exist in the same region that have available resources.

**Anything else we need to know?**:

Pod error:
Pod Node didn’t have enough resource: memory, requested: 1879048192, used: 66735570944, capacity: 67428761600
Reason: OutOfMemory

**Environment**:
- Kubernetes version (use `kubectl version`): v1.9.6+coreos.0
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): Linux
- Kernel (e.g. `uname -a`): 4.14.48-coreos-r2
- Install tools:
- Others: 
stork:1.1

**Comment by cehoffman** [comment]
This is a big in kube scheduler I think and this issue seems like exactly the issue we see. https://github.com/kubernetes/kubernetes/issues/60469

**Comment by disrani-px** [comment]
This was a bug in the kube-scheduler where the node caches for different scheduler instances would go out of sync causing pods to be scheduled on nodes which didn't have resources. Closing it since it has been fixed in the kube-scheduler since the issue was opened
