### ISSUE TITLE
Are Pod Topology Spread Constraints gonna be applied with Stork as well?

### ISSUE THREAD

**Issue by alifiroozi80** [libopenstorage/stork#1375]
Hello guys,

A very quick question:

I want to set the [Pod Topology Spread Constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints) on my manifests in order to use its advantages.

If I use `stork` as my `scheduler`, are does constraints gonna be applied?

**Comment by pp511** [comment]
Pod Topology spread is supported on K8s versions 1.23.0 and above. 
If you are using Operator based PX releases make sure to use Operator versions 1.10.3 and above.
If you are using Stork independently for testing, make sure to create a deployment which uses KubeSchedulerConfiguration. Reference stork deployment here: https://github.com/libopenstorage/stork/blob/master/specs/stork-deployment.yaml
