### ISSUE TITLE
Updation of a statefulset to use stork using kubectl replace doesnt bounce the application pods

### ISSUE THREAD

**Issue by hrishipx** [libopenstorage/stork#14]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
**What happened**:
Deployed Cassandra using https://docs.portworx.com/scheduler/kubernetes/cassandra-k8s.html
The pods get scheduled without Stork and there are some which are remotely mounted to the replicas. 

Apply an updated spec for cassandra using 
`kubectl replace -f cassandra-with-stork.yaml`
 
This does not restart the application pods to hyperconverge with the volumes.   

**What you expected to happen**:

Upon updation of the statefulset, the application pods should be bounced by stork and should hyperconverge with the volumes. 

**How to reproduce it (as minimally and precisely as possible)**:
- Follow https://docs.portworx.com/scheduler/kubernetes/cassandra-k8s.html 
- kubectl replace <spec for the statefulset with stork as the scheduler>

**Anything else we need to know?**:

If the application pod is manually deleted, the behaviour is correct. it generates a score and stork schedules the application to where the volume is. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.7.11
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu 16
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by disrani-px** [comment]
The scheduler will not reschedule any pods that are in running state even if the scheduler changes. We just need to document this behavior.

**Comment by disrani-px** [comment]
Closing bug, there is nothing we can do here for now
