### ISSUE TITLE
Restoring snapshots for a distributed application isnt supported

### ISSUE THREAD

**Issue by hr1sh1kesh** [libopenstorage/stork#16]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST
**What happened**:
Currently, you can restore the snapshot taken from Stork via the PVC. But in case of a distributed application which is deployed as a statefulset there cannot be a seperate PVC for each replica specified. 
Hence the capability of restoring snapshots for a distributed application should be at a higher abstraction than the current PVC setup. 

**What you expected to happen**:
Snapshotting and Restoring should be for an entire distributed application.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by disrani-px** [comment]
For stateful sets, the volume claims are specified as a template and a PVC name is created by the controller based on the name given in the template.
Are you suggesting the snapshotter should also use such templates? 
Right now snapshots can still be restored for stateful sets, the pvc that is created for the restore should match the templated names that the stateful set would generate.

**Comment by disrani-px** [comment]
Taking group snaps is being covered by Issue #78 , closing this bug
