### ISSUE TITLE
Reduce scale for group cloud snapshot load test

### ISSUE THREAD

**Issue by harsh-px** [libopenstorage/stork#269]
**BUG REPORT?**:

On slow setups, the https://github.com/libopenstorage/stork/tree/master/test/integration_test/specs/group-cloud-snap-load test takes upto 24 minutes causing the current tests to fail as they exceed timeouts

**What you expected to happen**:

The test should have passed.  The amount of data it writes needs to be reduced.

**Comment by disrani-px** [comment]
Closing as this is no longer needed
