### ISSUE TITLE
NoVolumeNodeConflict predicates has been removed

### ISSUE THREAD

**Issue by brokenmass** [libopenstorage/stork#34]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
**What happened**:
NoVolumeNodeConflict predicates has been removed as of k8s 1.9.3 and scheduler cannot start with default configuration

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use provided instruction to setup stork on k8s 1.9.3 cluster
related https://github.com/openshift/origin/issues/18527

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.3
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): RHEL 7
- Kernel (e.g. `uname -a`): 3.10.0-693.11.6.el7.x86_64

**Comment by disrani-px** [comment]
@brokenmass I had added a comment in the spec to make users aware of this

> The default list of predicates and priorities can change depending on your version
> of Kubernetes, so please update those as required. The requirement to manually specify this
> list will go away with Kubernetes v1.10 where it will use the defaults if nothing is
> specified.

There are users on 1.7, 1.8 and 1.9 so I've didn't remove it from the spec. An alternative would be to have different specs for each version but then that become a nightmare to maintain

**Comment by disrani-px** [comment]
@brokenmass Let me know if the above is fine or if you have any other suggestions.

**Comment by disrani-px** [comment]
Closing for now since this is documented in the spec and there has been no update in the bug.
