### ISSUE TITLE
New volume driver: LINSTOR

### ISSUE THREAD

**Issue by chrboe** [libopenstorage/stork#618]
[LINSTOR](https://github.com/LINBIT/linstor-server), developed by [LINBIT](https://linbit.com), is a Software-Defined Storage solution by LINBIT, makers of the popular DRBD distributed storage system.

As LINBIT expands its integration with the Kubernetes ecosystem, we have taken note of stork's popularity in the Kubernetes world, and we would like to contribute a stork volume driver for LINSTOR to the project.

We have a "half-baked" prototype driver available internally and would like to discuss the steps required to upstream it.

For instance, CONTRIBUTING.md mentions:
* Author(s) are expected to run all the integration tests with their driver and provide the logs of the result with the PR.

though I can't seem to find any documentation on how to actually run those integration tests.

We're looking forward to working on this with you!

**Comment by disrani-px** [comment]
Hi @chrboe,
Thanks for your interest in adding a driver to stork. Do you know what parts of the driver you are planning to support? (Snapshot, Migration, ApplicationBackup, etc)

Sorry, the instructions to run the test are missing. You would need to run test-deploy.sh from here: https://github.com/libopenstorage/stork/tree/master/test/integration_test
This script starts the stork and the stork test pods and takes in various parameters for both of them. If you let us know what features you are supporting with the driver we can help you run the appropriate tests.

The tests use the torpedo framework, so you'll need to add a basic driver there first, similar to the AWS driver: https://github.com/portworx/torpedo/tree/master/drivers/volume/aws

**Comment by chrboe** [comment]
I think for now we'll just be supporting the "core" features to keep things simple, so just the storage location optimization part. We can always add in the other parts later, but I think it would only make the upstreaming process more difficult now.

I will get to work on the torpedo driver and try to run the tests. Thanks for the help for now!

**Comment by chrboe** [comment]
Any updates here? Still not sure how to get integrate our driver in torpedo (see also the linked torpedo issue).

**Comment by disrani-px** [comment]
@chrboe I wasn't aware of the issue you raised in the torepdo repo. I've replied there. If you've implemented the driver there you should vendor that in here, create a directory with your storage class and start the test with your driver

**Comment by chrboe** [comment]
Thanks, I'll try that.

Regarding the `test-deploy.sh` script: surely this isn't expected to run on the host?

https://github.com/libopenstorage/stork/blob/0e091fb57413fbc5d52a9e127a91a8436c0e90e3/test/integration_test/test-deploy.sh#L128-L131

If so, what are these lines doing there?

What container would I run this script in?

**Comment by disrani-px** [comment]
@chrboe The script can be run on the host or from a container.
We run the script using `lachlanevenson/k8s-kubectl` container by mounting the script and specs inside the container

Something like this:
```
sudo docker run -t --net=host \
	    -v /home/admin/go/src/github.com/libopenstorage/stork/specs:/specs \
            -v /home/admin/go/src/github.com/libopenstorage/stork/test/integration_test/:/testspecs \
	     -v /home/admin/.kube/config:/tmp/kubeconfig \
	    -e KUBECONFIG=/tmp/kubeconfig \
            -e SSH_USERNAME=root \
     	    -e SSH_PASSWORD=password \
            --entrypoint /bin/sh \
            lachlanevenson/k8s-kubectl \
            /testspecs/test-deploy.sh \
```
