### ISSUE TITLE
Allow clone from snapshot into a different namespace

### ISSUE THREAD

**Issue by disrani-px** [libopenstorage/stork#71]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
1. Take snapshot in namespace N1
2. Try to create in PVC in namespace N2 from the snapshot in step 1. This will fail

**What you expected to happen**:
Should be allowed to clone snapshots to any allowed namespace.

- When creating the snapshot, take in a list of namespaces where it can be cloned.
- When creating the clone PVC, also take in the namespace of the snapshot.
- Make sure the PVC is allowed to be cloned in the namespace

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cehoffman** [comment]
This feature while not immediately something we could leverage is something that would be useful to us to enable better permissions control around production and staging/development versions of our services.
